FROM mysql:8.0

COPY database/init.sql      /docker-entrypoint-initdb.d/01-init.sql
COPY database/test-data.sql /docker-entrypoint-initdb.d/02-test-data.sql

RUN chmod 644 /docker-entrypoint-initdb.d/01-init.sql && \
    chmod 644 /docker-entrypoint-initdb.d/02-test-data.sql

EXPOSE 3306
